data:
  root: 'data'
  unknown_label: 0
  img_size: 32

dl:
  batch_size: 512
  num_workers: 0
  pin_memory: False
  persistent_workers: False

model:
  in_channels: 1
  embed_dim: 256

simple:
  b_theta: 0.3
  alpha: 0.001
  r: 2.
  m: 0.
  lw: 500.
  init_bias: -10.

train:
  num_bank: 16384
  ema_decay: 0.995
  max_grad_norm: 100
  amp: True
  device: 'cuda'

optimizer:
  momentum: 0.9
  encoder:
    lr: 0.1
    weight_decay: 0.0005
  simple:
    lr: 0.01
    weight_decay: 0.0005

scheduler:
    milestones: [2500, 5000, 7500]
    gamma: 0.1